services:
  # Web application
  webapp:
    image: tomcat:9.0-jdk11-openjdk-slim
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=webshop
      - DB_USER=root
      - DB_PASSWORD=webshop_password
    networks:
      - webshop-network
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT
      - ./target/classes:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=webshop_password
      - MYSQL_DATABASE=webshop
      - MYSQL_USER=webshop
      - MYSQL_PASSWORD=webshop_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./webshop.sql:/docker-entrypoint-initdb.d/webshop.sql
    networks:
      - webshop-network
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  webshop-network:
    driver: bridge
